spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${TRANSACTIONS_POSTGRES_DB:transactions_db}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:localdev}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: transaction-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.banking.events,java.lang,java.util"
        spring.json.use.type.headers: true
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://localhost:8081}
server:
  port: ${TRANSACTION_SERVICE_PORT:8082}
