package com.banking.notificationservice.service;

import com.banking.events.FraudDetectedEvent;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.kafka.core.KafkaTemplate;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.stereotype.Service;

import java.util.Map;

@Service
@Slf4j
public class NotificationService {
    /*
            Consumes the OTP Generated by TransactionEventConsumer
         */
    @KafkaListener(topics="transaction.otp.generated",groupId = "notification-service")
    public void consumeOTPGenerated(
            @Payload Map<String,Object> payload
    ){
        try{
            String accountNumber=(String)payload.get("accountNumber");
            String otp=(String) payload.get("otp");
            String transactionId=(String)payload.get("transactionId");
            String amount=(String)payload.get("amount");
            String reason=(String)payload.get("reason");
            sendAlert(accountNumber,"VERIFICATION REQUIRED",
                    "Suspicious Activity Detected on your Account"+
                    "Reason :%s .A transaction of %s is pending." +
                            "Your OTP is :%s." +
                            "Valid for 5 minutes."
                            );


        }catch(Exception e){
            log.error("Error sending OTP Notification : {}",e.getMessage());
        }
    }

    @KafkaListener(topics="transaction.completed")
    public void consumeTransactionCompleted(
            @Payload Map<String,Object> payload
    ){
        try{
            String senderAccount=(String)payload.get("senderAccountNumber");
            String receiverAccount=(String)payload.get("receiverAccountNumber");
            String amount=(String) payload.get("amount");

            //Debit Alert
            sendAlert(senderAccount,
                    "Money Debited",
                    String.format("%s debited from account : %s",amount,senderAccount));


            //Credit Alert
            sendAlert(receiverAccount,
                    "Money Credited",
                    String.format("%s credited to account : %s",amount,receiverAccount));
        }
        catch(Exception e ){
            log.error("Exception occurred while consumeTransactionCompleted : {}",e.getMessage());
        }
    }
@KafkaListener(topics = "fraud.detected")
    public void consumeFraudDetected(
        @Payload FraudDetectedEvent event
        ){
        try{

            String accountNumber=event.senderAccountNumber();
            String reason=event.reason();
            sendAlert(accountNumber,
                    "Suspicious Activity Detected",
                    String.format("Your account : %s has been blocked due to suspicious activity.\n Contact Your Bank Immediately.%s",accountNumber,reason));
        }
        catch(Exception e){
            log.error("Exception occurred while consumeFraudDetected : {}",e.getMessage());
        }
    }

    @KafkaListener(topics = "transaction.refunded")
    public void consumeRefundEvent(
        @Payload Map<String,Object> payload
                ){
        try{
            String senderAccount=(String) payload.get("senderAccount");
            String amount=(String) payload.get("amount");
            String reason=(String) payload.get("reason");
            sendAlert(senderAccount,
                    "Refund Processed",
                    String.format("Your transaction of %s was cancelled.\n%s has been refunded back to %s",amount,senderAccount));
        }catch(Exception e){
            log.error("Exception occurred while consumeRefundEvent  : {}",e.getMessage());
        }
    }



    /*
        Events sent by payment service
     */
    @KafkaListener(topics="payment.completed")
    public void consumePaymentCompleted(
        @Payload Map<String,Object> payload
    ){
        try{
            String accountNumber=(String) payload.get("accountNumber");
            String amount=(String) payload.get("amount");
            String razorpayPaymentId=(String) payload.get("razorpayPaymentId");
            sendAlert(accountNumber,
                    "Payment Successfull",
                    String.format("Payment for Payment Id : %s of %s completed from account : %s",razorpayPaymentId,amount,accountNumber));
        }catch(Exception e){
            log.error("Exception occurred while consumePaymentCompleted  : {}",e.getMessage());
        }
    }

    @KafkaListener(topics="payment.failed")
    public void consumePaymentFailed(
            @Payload Map<String,Object> payload
    ){
        try{
            String accountNumber=(String) payload.get("accountNumber");
            String amount=(String) payload.get("amount");
            sendAlert(accountNumber,
                    "Payment Failed",
                    String.format("Payment  of %s Failed.\n Try again and if it persists contact support.",amount));
        }catch(Exception e){
            log.error("Exception occurred while consumePaymentFailed  : {}",e.getMessage());
        }
    }
    private void sendAlert(String accountNumber,String subject,String message){


    }



}
