package com.banking.notificationservice.service;

import com.banking.events.*;
import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.stereotype.Service;

@Service
@Slf4j
public class NotificationService {
    /*
            Consumes the OTP Generated by TransactionEventConsumer
         */
    @KafkaListener(topics="transaction.otp.generated")
    public void consumeOTPGenerated(
            @Payload OTPGeneratedEvent otpGeneratedEvent
            ){
        try{
            String senderAccountNumber= otpGeneratedEvent.senderAccountNumber();
            String otp= otpGeneratedEvent.otp();
            String amount= otpGeneratedEvent.amount().toString();
            String reason= otpGeneratedEvent.reason();
            sendAlert(senderAccountNumber,"VERIFICATION REQUIRED",
                    "Suspicious Activity Detected on your Account"+
                    "Reason :"+reason+"." +
                            "A transaction of "+amount+" is pending." +
                            "Your OTP is : "+otp+
                            "Valid for 5 minutes."
                            );


        }catch(Exception e){
            log.error("Error sending OTP Notification : {}",e.getMessage());
        }
    }

    @KafkaListener(topics="transaction.completed")
    public void consumeTransactionCompleted(
            @Payload TransactionCompletedEvent transactionCompletedEvent
            ){
        try{
            String senderAccountNumber=transactionCompletedEvent.senderAccountNumber();
            String receiverAccountNumber=transactionCompletedEvent.receiverAccountNumber();
            String amount=transactionCompletedEvent.amount().toString();

            //Debit Alert
            sendAlert(senderAccountNumber,
                    "Money Debited",
                    String.format("%s debited from account : %s",amount,senderAccountNumber));


            //Credit Alert
            sendAlert(receiverAccountNumber,
                    "Money Credited",
                    String.format("%s credited to account : %s",amount,receiverAccountNumber));
        }
        catch(Exception e ){
            log.error("Exception occurred while consumeTransactionCompleted : {}",e.getMessage());
        }
    }
    @KafkaListener(topics = "transaction.failed")
    public void consumeTransactionFailed(
        @Payload TransactionFailedEvent transactionFailedEvent
                ){
        try{
            sendAlert(
                    transactionFailedEvent.senderAccountNumber(),
                    "Transaction Failed",
                    String.format(
                            "Transaction %s failed. Reason: %s",
                            transactionFailedEvent.transactionId(),
                            transactionFailedEvent.reason()
                    )
            );
        } catch(Exception e){
            log.error("Exception occurred while consuming transaction.failed: {}", e.getMessage());
        }
    }

    @KafkaListener(topics = "fraud.detected")
    public void consumeFraudDetected(
        @Payload FraudDetectedEvent fraudDetectedEvent
        ){
        try{

            String accountNumber=fraudDetectedEvent.senderAccountNumber();
            String reason=fraudDetectedEvent.reason();
            sendAlert(accountNumber,
                    "Suspicious Activity Detected",
                    String.format("Contact Your Bank Immediately if you didn't initiate a transaction from %s the reason was %s",accountNumber,reason));
        }
        catch(Exception e){
            log.error("Exception occurred while consumeFraudDetected : {}",e.getMessage());
        }
    }

    /*
        Events sent by payment service
     */
    @KafkaListener(topics="payment.completed")
    public void consumePaymentCompleted(
            @Payload PaymentCompletedEvent paymentCompletedEvent
            ){
        try{
            String senderAccountNumber=paymentCompletedEvent.senderAccountNumber();
            String amount=paymentCompletedEvent.amount().toString();
            String razorpayPaymentId=paymentCompletedEvent.razorpayPaymentId();
            sendAlert(senderAccountNumber,
                    "Payment Successfull",
                    String.format("Payment for Payment Id : %s of %s completed from account : %s",razorpayPaymentId,amount,senderAccountNumber));
        }catch(Exception e){
            log.error("Exception occurred while consumePaymentCompleted  : {}",e.getMessage());
        }
    }

    @KafkaListener(topics="payment.failed")
    public void consumePaymentFailed(
            @Payload PaymentFailedEvent paymentFailedEvent
    ){
        try{
            String senderAccountNumber=paymentFailedEvent.senderAccountNumber();
            String amount=paymentFailedEvent.amount().toString();
            sendAlert(senderAccountNumber,
                    "Payment Failed",
                    String.format("Payment  of %s Failed.\n Try again and if it persists contact support.",amount));
        }catch(Exception e){
            log.error("Exception occurred while consumePaymentFailed  : {}",e.getMessage());
        }
    }
    private void sendAlert(String accountNumber,String subject,String message){


    }



}
