package com.banking.notificationservice.service;

import lombok.extern.slf4j.Slf4j;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.stereotype.Service;

import java.util.Map;

@Service
@Slf4j
public class NotificationService {
    /*
        Consumes the OTP Generated by TransactionEventConsumer
     */
    @KafkaListener(topics="transaction.otp.generated",groupId = "notification-service")
    public void consumeOTPGenerated(
            @Payload Map<String,Object> payload
    ){
        try{
            String accountNumber=(String)payload.get("accountNumber");
            String otp=(String) payload.get("otp");
            String transactionId=(String)payload.get("transactionId");
            String amount=(String)payload.get("amount");
            String reason=(String)payload.get("reason");
            sendAlert(accountNumber,"VERIFICATION REQUIRED",
                    "Suspicious Activity Detected on your Account"+
                    "Reason :%s .A transaction of %s is pending." +
                            "Your OTP is :%s." +
                            "Valid for 5 minutes."
                            );


        }catch(Exception e){
            log.error("Error sending OTP Notification : {}",e.getMessage());
        }
    }

    private void sendAlert(String accountNumber,String subject,String message){

    }

}
