spring:
  application:
    name: fraud-detection-service
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: fraud-detection-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.banking.events,java.lang,java.util"
        spring.json.use.type.headers: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
fraud:
  max-transaction-per-minute: ${FRAUD_MAX_TRANSACTIONS_PER_MINUTE:5}
  suspicious_amount_multiplier: ${FRAUD_SUSPICIOUS_AMOUNT_MULTIPLIER:2}
  max_balance_percentage: ${FRAUD_MAX_BALANCE_PERCENTAGE:0.6}
account:
  service:
    url: ${ACCOUNT_SERVICE_URL:http://account-service:8081}
server:
  port: ${FRAUD_DETECTION_SERVICE_PORT:8084}
