spring:
  application:
    name: fraud-detection-service
  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      properties:
        spring.json.add.type.headers: true
    consumer:
      group-id: fraud-detection-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: "com.banking.events,java.lang,java.util"
        spring.json.use.type.headers: true
  data:
    redis:
      host: redis
      port: 6379
fraud:
  max-transaction-per-minute: 5
  suspicious_amount_multiplier: 2
  max_balance_percentage: 0.6
account:
  service:
    url: http://account-service:8081
server:
  port: 8084
management:
  endpoints:
    web:
      exposure:
        include: health,info
